# pyproject.toml
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "example_pypi"
version = "0.5.2"
dynamic = ["description", "requires-python", "authors", "classifiers"]

[project.optional-dependencies]
test = ["pytest", "coverage"]

